Repository LVMVRQUXL/CGG, pull requests merged in 2021-01, with the labels that each got.

#42 feature/36 into develop
  app/src/main/java/fr/esgi/rpa/cgg/question/QuestionActivity.kt
  app/src/main/res/layout/activity_colors.xml
  app/src/main/res/layout/activity_question.xml
  app/src/main/res/layout/activity_result.xml
  app/src/main/res/values/strings.xml
Labels: feature, review validated

#41 feature/35 into develop
  app/src/main/AndroidManifest.xml
  app/src/main/java/fr/esgi/rpa/cgg/MainActivity.kt
  app/src/main/java/fr/esgi/rpa/cgg/option/OptionActivity.kt
  app/src/main/res/drawable/rounded_corners_green.xml
  app/src/main/res/drawable/rounded_corners_red.xml
  app/src/main/res/drawable/rounded_corners_yellow.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_option.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feature, review validated

#45 Release/v0.4 into master
  .github/resources/APK_VERSION
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/assets/colors.json
  app/src/main/java/fr/esgi/rpa/cgg/MainActivity.kt
  app/src/main/java/fr/esgi/rpa/cgg/QuestionActivity.kt
  app/src/main/java/fr/esgi/rpa/cgg/color/Color.kt
  app/src/main/java/fr/esgi/rpa/cgg/color/ColorTimer.kt
  app/src/main/java/fr/esgi/rpa/cgg/color/ColorViewHolder.kt
  app/src/main/java/fr/esgi/rpa/cgg/color/ColorsActivity.kt
  app/src/main/java/fr/esgi/rpa/cgg/color/ColorsAdapter.kt
  app/src/main/java/fr/esgi/rpa/cgg/color/ColorsApiService.kt
  app/src/main/java/fr/esgi/rpa/cgg/color/ColorsRepository.kt
  app/src/main/java/fr/esgi/rpa/cgg/option/OptionActivity.kt
  app/src/main/java/fr/esgi/rpa/cgg/question/QuestionActivity.kt
  app/src/main/java/fr/esgi/rpa/cgg/result/ResultActivity.kt
  app/src/main/res/drawable/rounded_corners_green.xml
  app/src/main/res/drawable/rounded_corners_red.xml
  app/src/main/res/drawable/rounded_corners_yellow.xml
  app/src/main/res/layout/activity_colors.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_option.xml
  app/src/main/res/layout/activity_question.xml
  app/src/main/res/layout/color_item.xml
  app/src/main/res/layout/question_page.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/network_security_config.xml
  build.gradle
Labels: release, review validated

#44 Release/v0.4 into develop
  .github/resources/APK_VERSION
Labels: pending review, release

#49 Feature/37 into develop
  app/src/main/AndroidManifest.xml
  app/src/main/java/fr/esgi/rpa/cgg/MainActivity.kt
  app/src/main/java/fr/esgi/rpa/cgg/color/Color.kt
  app/src/main/java/fr/esgi/rpa/cgg/color/ColorViewHolder.kt
  app/src/main/java/fr/esgi/rpa/cgg/color/ColorsActivity.kt
  app/src/main/java/fr/esgi/rpa/cgg/color/ColorsAdapter.kt
  app/src/main/java/fr/esgi/rpa/cgg/color/ColorsApiService.kt
  app/src/main/java/fr/esgi/rpa/cgg/color/ColorsRepository.kt
  app/src/main/java/fr/esgi/rpa/cgg/color/GetColorsCallback.kt
  app/src/main/java/fr/esgi/rpa/cgg/color/SingleColor.kt
  app/src/main/java/fr/esgi/rpa/cgg/color/SuggestionColors.kt
  app/src/main/java/fr/esgi/rpa/cgg/difficulty/DifficultyActivity.kt
  app/src/main/java/fr/esgi/rpa/cgg/difficulty/DifficultyPreferences.kt
  app/src/main/java/fr/esgi/rpa/cgg/option/OptionActivity.kt
  app/src/main/java/fr/esgi/rpa/cgg/question/QuestionActivity.kt
  app/src/main/java/fr/esgi/rpa/cgg/quiz/Question.kt
  app/src/main/java/fr/esgi/rpa/cgg/quiz/QuizActivity.kt
  app/src/main/java/fr/esgi/rpa/cgg/quiz/QuizManager.kt
  app/src/main/java/fr/esgi/rpa/cgg/result/ResultActivity.kt
  app/src/main/java/fr/esgi/rpa/cgg/utils/ButtonUtils.kt
  app/src/main/res/drawable-v24/rounded_corners_complementary.xml
  app/src/main/res/drawable/rounded_corners_green.xml
  app/src/main/res/drawable/rounded_corners_primary.xml
  app/src/main/res/drawable/rounded_corners_primary_dark.xml
  app/src/main/res/drawable/solid_oval.xml
  app/src/main/res/layout/activity_colors.xml
  app/src/main/res/layout/activity_difficulty.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_quiz.xml
  app/src/main/res/layout/activity_result.xml
  app/src/main/res/layout/color_item.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feature, review validated

#51 Feature/46 into develop
  app/build.gradle
  app/src/main/java/fr/esgi/rpa/cgg/BaseActivity.kt
  app/src/main/java/fr/esgi/rpa/cgg/MainActivity.kt
  app/src/main/java/fr/esgi/rpa/cgg/color/ColorsActivity.kt
  app/src/main/java/fr/esgi/rpa/cgg/difficulty/DifficultyActivity.kt
  app/src/main/java/fr/esgi/rpa/cgg/quiz/QuizActivity.kt
  app/src/main/java/fr/esgi/rpa/cgg/result/ResultActivity.kt
  app/src/main/java/fr/esgi/rpa/cgg/utils/InternetCheck.kt
  app/src/main/res/layout/activity_colors.xml
  app/src/main/res/layout/activity_difficulty.xml
  app/src/main/res/values/strings.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: feature, review validated

#52 Feature/34 into develop
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/fr/esgi/rpa/cgg/MainActivity.kt
  app/src/main/java/fr/esgi/rpa/cgg/result/ResultActivity.kt
  app/src/main/java/fr/esgi/rpa/cgg/score/Score.kt
  app/src/main/java/fr/esgi/rpa/cgg/score/ScoreViewHolder.kt
  app/src/main/java/fr/esgi/rpa/cgg/score/ScoresActivity.kt
  app/src/main/java/fr/esgi/rpa/cgg/score/ScoresAdapter.kt
  app/src/main/java/fr/esgi/rpa/cgg/score/ScoresCsvManager.kt
  app/src/main/res/layout/activity_difficulty.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_scores.xml
  app/src/main/res/layout/score_item.xml
  app/src/main/res/values/strings.xml
Labels: feature, review validated

#54 Release v0.5.0 into develop
  .github/resources/APK_VERSION
Labels: release, review validated

#57 Feature/38 into develop
  app/src/main/java/fr/esgi/rpa/cgg/MainActivity.kt
  app/src/main/java/fr/esgi/rpa/cgg/result/ResultActivity.kt
  app/src/main/java/fr/esgi/rpa/cgg/score/Score.kt
  app/src/main/java/fr/esgi/rpa/cgg/score/ScoreViewHolder.kt
  app/src/main/java/fr/esgi/rpa/cgg/score/ScoresActivity.kt
  app/src/main/java/fr/esgi/rpa/cgg/score/ScoresCsvManager.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
Labels: feature, request changes

#58 Feature/50 into develop
  app/build.gradle
  app/src/main/java/fr/esgi/rpa/cgg/color/ColorsActivity.kt
  app/src/main/java/fr/esgi/rpa/cgg/quiz/QuizManager.kt
Labels: feature, review validated

#60 Release/v1.0.0 into master
  .github/resources/APK_VERSION
  app/build.gradle
  app/src/main/java/fr/esgi/rpa/cgg/MainActivity.kt
  app/src/main/java/fr/esgi/rpa/cgg/color/ColorsActivity.kt
  app/src/main/java/fr/esgi/rpa/cgg/quiz/QuizActivity.kt
  app/src/main/java/fr/esgi/rpa/cgg/quiz/QuizManager.kt
  app/src/main/java/fr/esgi/rpa/cgg/result/ResultActivity.kt
  app/src/main/java/fr/esgi/rpa/cgg/score/Score.kt
  app/src/main/java/fr/esgi/rpa/cgg/score/ScoreViewHolder.kt
  app/src/main/java/fr/esgi/rpa/cgg/score/ScoresActivity.kt
  app/src/main/java/fr/esgi/rpa/cgg/score/ScoresCsvManager.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
Labels: release, review validated

#59 Release/v1.0.0 into develop
  .github/resources/APK_VERSION
  app/src/main/java/fr/esgi/rpa/cgg/quiz/QuizActivity.kt
  app/src/main/java/fr/esgi/rpa/cgg/score/ScoresActivity.kt
Labels: release, review validated
